version: '3.1'
services:
  postgresql-server:
    container_name: postgresql-server
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: app-transaction
      POSTGRES_USER: app-transaction
    ports:
      - "5432:5432"
  app-transaction:
    container_name: app-transaction
    build: .
    environment:
      POSTGRESQL_URL: jdbc:postgresql://postgresql-server/app-transaction
      POSTGRESQL_USERNAME: app-transaction
      POSTGRESQL_PASSWORD: app-transaction
    ports:
      - "8080:8080"
    depends_on:
      - postgresql-server